### ISSUE TITLE
After upgrading to 1.3.0 the report is missing details about the vulnerable dependencies

### ISSUE THREAD

**Issue by szymonbultrowicz** [davityavryan/yarn-audit-html#16]
Hey,

After upgrading to version 1.3.0 all the entries are now grouped depending only on the vulnerability type. I understand the reasoning, however it's now missing all the details about which version causes the issue and which libraries are using the unsafe dependency. For example, the v1.3.0 report would produce a single entry of:
![image](https://user-images.githubusercontent.com/9554528/88043555-e13ccd00-cb4d-11ea-8738-40c27bd27e02.png)
However, in fact, I know that I'm using multiple vulnerable versions of yargs-parser that are transitive dependencies of other libs (and it's also what I would get from version 1.2.x). That information is not available anymore.

What do you think of extending the UI to cover this scenario or adding a command line flag to switch between those 2 grouping strategies?

**Comment by davityavryan** [comment]
Hi @szymonbultrowicz 
I will take a look ASAP. Meanwhile can you be so kind to share the `yarn audit --json` results please?

**Comment by davityavryan** [comment]
Hey @szymonbultrowicz.

1.3.0 is fixing a problem in which vulnerabilities were grouped wrongly. for example `jquery@1.12.0` has two vulnerabilities (`CWE-471` and `CWE-79`) and they were merged together because calculations previously were grouped by `PACKAGE_NAME@VERSION` but starting from 1.3.0 I am using `CWE` as a key for grouping them.

So I would really appreciate if you will share audit JSONL file so that I can compare and understand what's the problem.

BTW there is a flag `--no-unique` maybe that will help you :/

Here are screenshots of previous and current versions for one of my test JSONL files

v1.2.3
![localhost_63342_yarn-audit-html_yarn-audit 1 2 3 ignore html__ijt=e3h59235vkrnr3leolakipcg4o](https://user-images.githubusercontent.com/8176311/88108205-c186c280-cba8-11ea-9cfd-aa052933b6af.png)

v1.3.0
![localhost_63342_yarn-audit-html_yarn-audit html__ijt=e3h59235vkrnr3leolakipcg4o](https://user-images.githubusercontent.com/8176311/88108240-cc415780-cba8-11ea-93d5-fe18ca4c0ba9.png)

v1.3.0 with `--no-unique` flag on
![localhost_63342_yarn-audit-html_yarn-audit 1 3 0-no-unique ignore html__ijt=diekl00h2pncl7etsi68h8389v](https://user-images.githubusercontent.com/8176311/88108268-d82d1980-cba8-11ea-8d1b-8f59c890be61.png)

**Comment by szymonbultrowicz** [comment]
Thanks @davityavryan!

Here is the content of my audit json file: 
[audit.json.txt](https://github.com/davityavryan/yarn-audit-html/files/4956326/audit.json.txt)
(Github apparently doesn't allow attaching json files...)

**Comment by davityavryan** [comment]
I see it now. thanks for reporting. will try to fix ASAP. ;)

**Comment by davityavryan** [comment]
try 1.3.1 ;)

**Comment by davityavryan** [comment]
I might introduce grouping in coming versions. thanks for the hint. ;)

**Comment by szymonbultrowicz** [comment]
Hey, thanks for so quick response! Now it works much better :) However, I still see an issue, because the "reasons" are not complete, see:
![image](https://user-images.githubusercontent.com/9554528/88111532-5d66fd00-cbae-11ea-9031-8d133137da1b.png)
According to the json, the version 9.0.2 is used by `@nrwl/workspace>yargs>yargs-parser` and `@nrwl/workspace>@nrwl/cli>yargs>yargs-parser` however, in the html, there is only one "reason".
I think it was working correctly some time ago and I could see the full list.

**Comment by davityavryan** [comment]
Ah, yes. :)
The whole point of this issue. My bad. try `1.3.2`

Although I would prefer change default behaviour to use only `CWE` as a key. Maybe in the future version, when I will introduce grouping I might consider changing it back (will bump MAJOR).

Feel free to close if that fixed your problem.

**Comment by szymonbultrowicz** [comment]
Yep, that works like a charm :) Thanks again.

**Comment by davityavryan** [comment]
You are welcome. ;)
