### ISSUE TITLE
Add a --title parameter

### ISSUE THREAD

**Issue by EliuX** [davityavryan/yarn-audit-html#3]
I am creating different reports and it would be nice if I could specify an optional parameter `--title` or `-t` to indicate a title different to "Yarn Audit Report".
E.g.
```
yarn audit --json | yarn-audit-html -t "New issues to solve"
```
Which would generate something like

![image](https://user-images.githubusercontent.com/6514740/58204569-23485580-7ca2-11e9-93fa-73efd9063d55.png)

**Comment by davityavryan** [comment]
Hi @EliuX,

Thanks for a suggestion. There is a [non documented option](https://github.com/davityavryan/yarn-audit-html/blob/679a78be81255397807be1a8ed4f5f1e8c323188/index.js#L10) which might help you. You can use your own template for report and customise the way that you want. **Sounds ok?**

I don't want to add your suggested option not because I am lazy but because the request is not generic. I might say that it would make sense also to have ability for user to specify sub header format.

p.s. Sorry that the option was not documented. I will add that.

**Comment by EliuX** [comment]
Thanks for the soon replay @davityavryan. Yes, I saw when using `--help` that such option was there. But I actually just need the same template as you use, but just to customize the only part that is fixed in that template. But don't worry, I understand your argument. Thanks indeed.
